### ISSUE TITLE
Getting 'AttributeError: module 'pandas.io.parsers' has no attribute 'base_parser'' while trying to read a csv file using  modin.pandas. Pls find the error below ....................also i had installed all the upgraded versions.

### ISSUE THREAD

**Issue by dsgit2020** [modin-project/modin-tutorial#4]
@_inherit_docstrings(pandas.io.parsers.base_parser.ParserBase._validate_usecols_arg)
AttributeError: module 'pandas.io.parsers' has no attribute 'base_parser'

**Comment by devin-petersohn** [comment]
Hi @AspirnQnt, thanks for posting!

Is this error coming from one of the tutorials? If so, with which tutorial did you have the problem?
